apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-service
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: production
  system: example-system
  dependsOn:
    - component:another-service